# Site settings
author: Chris Grannan
title: My Data Journey
header-img: img/home-bg.png
email: cmgrannan88@gmail.com
copyright_name: Chris Grannan
description: > # this means to ignore newlines until "baseurl:"
  Learning Data Science
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  CGrannan

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
